src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column]
    private ?float $Monnaie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getMonnaie(): ?float
    {
        return $this->Monnaie;
    }

    public function setMonnaie(float $Monnaie): self
    {
        $this->Monnaie = $Monnaie;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }


    #[ORM\Column]
    private ?int $Quete = null;

    public function getQuete(): ?int
    {
        return $this->Quete;
    }

    public function setQuete(int $Quete): self
    {
        $this->Quete = $Quete;

        return $this;
    }
}

src/Controller/GestCmptController.php
<?php

namespace App\Controller;

use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class GestCmptController extends AbstractController
{
    #[Route('/gest/cmpt', name: 'app_gest_cmpt', methods: ['GET'])]
    public function index(UserRepository $repository): Response
    {
        // On bloque la page pour les personnes qui ne sont pas admin
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        
        return $this->render('pages/gest_cmpt/index.html.twig', [
            'controller_name' => 'GestCmptController',
            'comptes' => $repository->findAll()
        ]);
    }
}

templates/pages/gest_cmpt/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion comptes{% endblock %}

{% block body %}
<div class="container mt-4">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nom</th>
        <th scope="col">Prenom</th>
        <th scope="col">ID</th>
        <th scope="col">Email</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for compte in comptes %}
        <tr>
          <td>{{ compte.nom }}</td>
          <td>{{ compte.prenom }}</td>
          <td>{{ compte.id }}</td>
          <td>{{ compte.email }}</td>
          <td>
              <div class="d-flex justify-content-between">
                <form method="POST" action="{{ path('profil') }}">
                  <input type="hidden" name="id" value="{{ compte.id }}">
                  <input type="hidden" name="action" value="see">
                  <button type="submit" class="btn btn-info">Voir</button>
                </form>
                <button type="button" class="btn btn-warning" onclick="window.location.href='{{ path('profil_update', {'id': compte.id}) }}'">Modifier</button>
                <button type="button" class="btn btn-danger" onclick="if (confirm('Voulez-vous vraiment supprimer ce compte ?')) { window.location.href='{{ path('profil_delete', {'id': compte.id}) }}' }">Supprimer</button>
              </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/pages/gest_cmpt/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur{% endblock %}

{% block body %}
<div class = "container mt-4">
        <h1 class="text-center">Modification de l'utilisateur {{ user.nom }}</h1>
        <form method="POST" action="" enctype="multipart/form-data">
            <div class="form-group">
                <label for="nom">Nom</label>
                <input type="text" class="form-control" id="nom" name="nom" placeholder="Nom" value="{{ user.nom }}">
            </div>
            <div class="form-group">
                <label for="prenom">Prénom</label>
                <input type="text" class="form-control" id="prenom" name="prenom" placeholder="Prénom" value="{{ user.prenom }}">
            </div>
            <div class="form-group">
                <label for="email">Adresse email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Adresse email" value="{{ user.email }}">
            </div>
            <div class="form-group">
                <label for="image">Photo</label>
                <input type="file" class="form-control" id="photo" name="photo" placeholder="Photo" accept="image/png, image/jpeg, image/jpg">
                {% if item is defined %}
                    <input type="hidden" name="old_photo" value="{{ user.photo }}">
                {% endif %}
            </div>
            <input type="hidden" name="id" value="{{ user.id }}">
            <button type="submit" class="btn btn-primary">Modifier</button>
        </form>

</div>
{% endblock %}