src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ItemRepository::class)]
class Item
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $stat = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $qte = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?float $Prix = null;

    #[ORM\ManyToOne(inversedBy: 'items')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TypeItem $typeItem = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getStat(): ?string
    {
        return $this->stat;
    }

    public function setStat(string $stat): self
    {
        $this->stat = $stat;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getQte(): ?string
    {
        return $this->qte;
    }

    public function setQte(string $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getTypeItem(): ?TypeItem
    {
        return $this->typeItem;
    }

    public function setTypeItem(?TypeItem $typeItem): self
    {
        $this->typeItem = $typeItem;

        return $this;
    }
}

src/Controller/GestBoutiqueController.php
<?php

namespace App\Controller;

use App\Repository\ItemRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class GestBoutiqueController extends AbstractController
{
    #[Route('/gest/boutique', name: 'app_gest_boutique',  methods: ['GET'])]
    public function index(ItemRepository $repository): Response
    {
        // On bloque la page pour les personnes qui ne sont pas admin
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        return $this->render('pages/gest_boutique/index.html.twig', [
            'controller_name' => 'GestBoutiqueController',
            'items' => $repository->findAll()
        ]);
    }
}

templates/pages/gest_boutique/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion boutique{% endblock %}

{% block body %}
<div class="container mt-4">
  <h1 class="text-center">Gestion des items de la boutique</h1>
  <!-- On créé un bouton d'ajout d'item qui renvoit vers item_create-->
  <button type="button" class="btn btn-success" onclick="window.location.href='{{ path('item_create') }}'">Ajouter un item</button>
  <button type="button" class="btn btn-success" onclick="window.location.href='{{ path('type_item_create') }}'">Ajouter un type d'item</button>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Image</th>
        <th scope="col">Nom de l'item</th>
        <th scope="col">Description</th>
        <th scope="col">Quantité</th>
        <th scope="col">Prix</th>
        <th scope="col">Type</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
        <tr>
          <td><img src="/images/items/{{ item.url }}" class="card-img-top" alt="Image de l'item" style="max-height: 100px; max-width: 100px;"></td>
          <td>{{ item.nom }}</td>
          <td>{{ item.description }}</td>
          <td>{{ item.qte }}</td> 
          <td>{{ item.prix }}</td>
          <td>{{ item.typeItem.nomTypeItem }}</td>
          <td>
            <div class="d-flex justify-content-between">
              <form method="POST" action="{{ path('item') }}">
                <input type="hidden" name="id" value="{{ item.id }}">
                <input type="hidden" name="action" value="update">
                <button type="submit" class="btn btn-warning">Modifier</button>
              </form>
              <form method="POST" action="{{ path('item') }}">
                <input type="hidden" name="id" value="{{ item.id }}">
                <input type="hidden" name="action" value="delete">
                <button type="submit" class="btn btn-danger">Supprimer</button>
              </form>
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}